import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "../styles/global.css";
import Navigation from "../components/navigation/navigation";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
